:base_url = http://localhost:8081

GET :base_url/tokenz
-> run-hook (restclient-set-var ":newtoken" (cdr (assq 'token (json-read))))

#

POST http://localhost:8081/todos
Authorization: Bearer :newtoken
Content-Type: application/json

{
    "text": "test 7"
}
